#!/usr/bin/env python3
"""Render the arm B ontologies as Mermaid class diagrams.

Entity types become classes, their `fields` become attributes, relation types
become associations labelled with the predicate, and `extends` becomes
inheritance. Generated from the YAML so the diagrams cannot drift from the
ontologies they document.

Usage: ontology_mermaid.py [--out FILE]
"""
import argparse, glob, json, os, yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ONT = os.path.join(HERE, "ontologies")

# Mermaid association arrows carry meaning; use the strongest one each
# relation's axioms justify.
def arrow(r):
    if r.get("symmetric"):
        return "--"          # undirected
    if r.get("transitive") or r.get("acyclic"):
        return "-->"
    return "-->"

def cls(name):
    """Mermaid class ids cannot contain spaces or punctuation."""
    return "".join(ch for ch in name if ch.isalnum() or ch == "_")

def diagram(doc, title):
    ents = doc.get("entity_types") or []
    rels = doc.get("relation_types") or []
    streams = doc.get("streams") or []
    by_stream = {}
    for s in streams:
        for t in (s.get("entity_types") or []):
            by_stream[t] = s["name"]

    L = ["classDiagram", "    direction LR"]

    for e in ents:
        n = cls(e["name"])
        body = []
        for f in (e.get("fields") or []):
            body.append(f"        +{f['key']}")
        if e.get("irreducible"):
            body.append("        <<irreducible>>")
        if body:
            L.append(f"    class {n} {{")
            L += body
            L.append("    }")
        else:
            L.append(f"    class {n}")
        if e["name"] in by_stream:
            L.append(f"    note for {n} \"stream: {by_stream[e['name']]}\"")

    declared = {cls(e["name"]) for e in ents}
    seen = set()
    for r in rels:
        doms = r.get("domain") or []
        rngs = r.get("range") or []
        if not doms or not rngs:
            continue
        # One edge per predicate keeps the diagram readable; extra domain/range
        # members are shown in the label rather than as a combinatorial mesh.
        d, g = cls(doms[0]), cls(rngs[0])
        if (d, g, r["name"]) in seen:
            continue
        seen.add((d, g, r["name"]))
        for x in (d, g):
            if x not in declared:
                L.append(f"    class {x}")
                declared.add(x)
        tag = r["name"]
        marks = []
        if r.get("transitive"): marks.append("trans")
        if r.get("acyclic"):    marks.append("acyclic")
        if r.get("functional"): marks.append("1")
        if r.get("symmetric"):  marks.append("sym")
        if len(doms) > 1 or len(rngs) > 1:
            marks.append("+")
        if marks:
            tag += f" [{','.join(marks)}]"
        L.append(f"    {d} {arrow(r)} {g} : {tag}")
    return "\n".join(L)

def inheritance(docs):
    L = ["classDiagram", "    direction TB"]
    for name, d in docs.items():
        o = d.get("ontology") or {}
        parent = o.get("extends")
        me = cls(name)
        L.append(f"    class {me}")
        if parent and parent != "none":
            L.append(f"    {cls(parent)} <|-- {me}")
    return "\n".join(L)



# ── HTML artifact generation ─────────────────────────────────────────────────

def load_metrics():
    """Pull clean-rate and relation density from the arm A / hygiene results."""
    def newest(pat):
        f = sorted(glob.glob(os.path.join(HERE, "results", pat)))
        return json.load(open(f[-1])) if f else []
    hyg = {r["kb"]: r for r in newest("corpus_hygiene_*.json")}
    base = {r["kb"]: r for r in (newest("ontology_baseline_2026*.json") or {}).get("kbs", [])}
    return hyg, base

def status_for(kb, hyg, base):
    h = hyg.get(kb); b = base.get(kb)
    if not h or not b:
        return ("module", "shared module", "")
    clean = h["clean_rate"]; dens = b.get("relations_per_entity") or 0
    if clean < 0.8:
        return ("blocked", "blocked on ingestion",
                f"{clean*100:.0f}% clean text — fix ingestion before applying")
    if dens < 0.01:
        return ("apply", "apply first",
                f"{clean*100:.0f}% clean, {dens:.4f} rel/ent — vocabulary-bound")
    return ("productive", "already productive",
            f"{clean*100:.0f}% clean, {dens:.4f} rel/ent")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(HERE, "ontology_diagrams.md"))
    a = ap.parse_args()
    docs = {}
    for f in sorted(glob.glob(os.path.join(ONT, "*.yaml"))):
        n = os.path.basename(f)[:-5]
        docs[n.replace("_module_", "").replace("_", "-")] = yaml.safe_load(open(f))
    out = ["# Ontology class diagrams\n",
           "Generated by `ontology_mermaid.py` from `ontologies/*.yaml`.\n",
           "## Module inheritance\n", "```mermaid", inheritance(docs), "```\n"]
    for n, d in docs.items():
        if not (d.get("entity_types") or d.get("relation_types")):
            continue
        out += [f"## {n}\n", "```mermaid", diagram(d, n), "```\n"]
    open(a.out, "w").write("\n".join(out))
    print(a.out)

if __name__ == "__main__":
    main()
